// baebiniSpace/eter/eternal-return-info-nuxt/components/Navbar.vue
<template>
  <nav class="bg-gray-800 p-4 shadow-md">
    <div class="container mx-auto flex justify-between items-center">
      <NuxtLink to="/" class="text-white text-2xl font-bold">
        이터널 리턴 정보
      </NuxtLink>
      <div class="space-x-6">
        <NuxtLink to="/" class="text-gray-300 hover:text-white transition-colors">
          홈
        </NuxtLink>
        <NuxtLink to="/characters" class="text-gray-300 hover:text-white transition-colors">
          실험체
        </NuxtLink>
      </div>
    </div>
  </nav>
</template>

<script setup>
</script>

// baebiniSpace/eter/eternal-return-info/src/components/Navbar.tsx
import Link from 'next/link';

export default function Navbar() {
  return (
    <nav className="bg-gray-800 p-4 shadow-md">
      <div className="container mx-auto flex justify-between items-center">
        <Link href="/" className="text-white text-2xl font-bold">
          이터널 리턴 정보
        </Link>
        <div className="space-x-6">
          <Link href="/" className="text-gray-300 hover:text-white transition-colors">
            홈
          </Link>
          <Link href="/characters" className="text-gray-300 hover:text-white transition-colors">
            실험체
          </Link>
          {/* TODO: 루트 등 다른 카테고리 링크 추가 */}
        </div>
      </div>
    </nav>
  );
}
